CREATE TABLE IF NOT EXISTS `class` (
  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `name` TEXT NOT NULL,
  `role` TEXT NOT NULL UNIQUE,
  `group` INTEGER,
  `channel` TEXT NOT NULL UNIQUE,
  FOREIGN KEY(`group`) REFERENCES `group`(`id`) ON UPDATE CASCADE ON DELETE CASCADE
);