CREATE TABLE IF NOT EXISTS `group` (
  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `name` TEXT NOT NULL COLLATE NOCASE,
  `channel_group` TEXT NOT NULL UNIQUE,
  `vc` TEXT NOT NULL UNIQUE
);